  server {
        listen 80;
        server_name admin.lumi-insert.com; 
 
        location / {
            proxy_pass http://grafana:3000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    } 

    server {
        listen 80;
        server_name lumi-insert.com; 
 
        set $cors_origin $allowed_origin;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization; 
 
        location /api/auth/ {
            limit_req zone=auth_limit burst=3 nodelay; 
            include general.inc; 
            limit_req_status 429;
            proxy_pass http://app:8080;
        }

        location ~ ^/(.*)/(export|pdf)$ {
            limit_req zone=auth_limit burst=2 nodelay; 
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
            proxy_buffering off;
            include general.inc; 
            limit_req_status 429;
            proxy_pass http://app:8080;
        }

        location /api/ {
            limit_req zone=general_limit burst=15 nodelay;
            include general.inc; 
            limit_req_status 429;
            proxy_pass http://app:8080;
        }

        location /swagger-ui/ { 
            proxy_pass http://app:8080;
        }

        location /v3/ { 
            proxy_pass http://app:8080;
        }
    } 