spring.application.name=LUMI Insert Java Edition

spring.datasource.core.url=jdbc:postgresql://localhost:5432/lumijava?stringtype=unspecified
spring.datasource.core.username=developer
spring.datasource.core.password=082383
spring.datasource.core.driver-class-name=org.postgresql.Driver
spring.datasource.core.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.core.hikari.minimum-idle=5
spring.datasource.core.hikari.maximum-pool-size=10

spring.datasource.activitycore.url=jdbc:postgresql://localhost:5432/lumijava?stringtype=unspecified
spring.datasource.activitycore.username=developer
spring.datasource.activitycore.password=082383
spring.datasource.activitycore.driver-class-name=org.postgresql.Driver
spring.datasource.activitycore.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.activitycore.hikari.minimum-idle=2
spring.datasource.activitycore.hikari.maximum-pool-size=5

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

server.forward-header-strategy=native

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=1

spring.jpa.hibernate.ddl-auto=validate

spring.config.import=optional:file:.env[.properties]
org.hibernate.envers.store_data_at_delete= true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SMTP_MAIL_USERNAME}
spring.mail.password=${SMTP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

super.admin.password=${SUPER_ADMIN_PASSWORD}

cloudinary.setup.url=${CLOUDINARY_URL}
