spring.application.name=LUMI Insert Java Edition

spring.datasource.core.url=jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?stringtype=unspecified
spring.datasource.core.username=${POSTGRES_USER}
spring.datasource.core.password=${POSTGRES_PASSWORD}
spring.datasource.core.driver-class-name=org.postgresql.Driver
spring.datasource.core.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.core.hikari.minimum-idle=5
spring.datasource.core.hikari.maximum-pool-size=10

spring.datasource.activitycore.url=jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?stringtype=unspecified
spring.datasource.activitycore.username=${POSTGRES_USER}
spring.datasource.activitycore.password=${POSTGRES_PASSWORD}
spring.datasource.activitycore.driver-class-name=org.postgresql.Driver
spring.datasource.activitycore.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.activitycore.hikari.minimum-idle=2
spring.datasource.activitycore.hikari.maximum-pool-size=5

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

server.forward-header-strategy=native

spring.threads.virtual.enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=1

spring.jpa.hibernate.ddl-auto=validate

spring.config.import=optional:file:.env[.properties]
org.hibernate.envers.store_data_at_delete= true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SMTP_MAIL_USERNAME}
spring.mail.password=${SMTP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

super.admin.password=${SUPER_ADMIN_PASSWORD}

cloudinary.setup.url=${CLOUDINARY_URL}

management.endpoints.web.exposure.include=health,info,prometheus
app.aop.enabled=true

app.jwt.secret=${ALGORITHM_JWT}
