package lumi.insert.app.core.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.github.f4b6a3.uuid.UuidCreator;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;

import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lumi.insert.app.core.entity.nondatabase.BaseAuditing; 

/**
 * Representation class of database table {@code"auth_tokens"}. 
 * <p>Store credential informations such as token, Employee and token expired date.<br>
 * Class can be implemented by{@code NoArgsConstructor, AllArgsConstructor and Builder}. </p>
 * 
 * @author KelvinKhodes
 * @since 1.0.0 
 */
@Entity(name = "auth_tokens")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
@Data
@Audited
public class AuthToken extends BaseAuditing{

    /**
     * Unique identifier of entity .
     * <p>Strongly recommend to assign manually use {@link UuidCreator#getTimeOrderedEpochFast()}.</p>
     */
    @Id
    @NotAudited
    private UUID id;  

    /**
     * Token used to identify credentials and generate access token .
     ** <p>Generated by {@link UuidCreator#getTimeOrderedEpochFast()} .<br> Important: must not null and unique.</p> 
     */
    @Column(nullable = false, unique = true)
    private String refreshToken; 

    /**
     * Relation to {@link Employee} (employees).
     * <p>{@link OneToOne} related, means an AuthToken can only related to an Employee and otherwise. </p>
     ** <p>Important: must not null and unique.</p> 
     */
    @OneToOne 
    @NotAudited
    private Employee employee;

    /**
     * Contains exact Time when AuthToken is expired. 
     ** <p>Important: must not null.</p> 
     */
    @Column(nullable = false)
    private LocalDateTime expiredAt; 
}
