package lumi.insert.app.core.entity;

import java.util.List;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited; 

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import lumi.insert.app.core.entity.nondatabase.BaseAuditing;

/**
 * Representation class of database table {@code"categories"}. 
 * <p>Store informations such as category name, total products related and category status.<br>
 * Class can be implemented by{@code NoArgsConstructor, AllArgsConstructor and Builder}. </p>
 * 
 * @author KelvinKhodes
 * @since 1.0.0 
 */
@Entity(name = "categories")
@Data
@EqualsAndHashCode(callSuper = false)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Audited
public class Category extends BaseAuditing {

    /**
     * Unique identifier of entity .
     * <p>Auto generated by {@link  GeneratedValue} with {@link GenerationType#IDENTITY} strategy. Note: Assignment trigger after Entity saved</p>
     */
    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY) 
    private Long id;

    /**
     * Category name. 
     ** <p>Important: must not null and unique.</p> 
     */
    @Column(unique = true, nullable = false)
    private String name;

    /**
     * List of relation to {@link Product} (products).
     * <p>{@link OneToMany} related, means a Category can related to more than one Product. </p>
     ** <p>Important: must not null and unique.</p> 
     */
    @OneToMany(mappedBy = "category")
    @ToString.Exclude
    @NotAudited
    private List<Product> product;

    /**
     * Total products related, count by increment each product saved. 
     ** <p>Note: Default value is 0</p> 
     */
    @Builder.Default
    private Long totalItems = 0L;

    /**
     * Category active status. If false, this category will not appear when searched. 
     ** <p>Note: Default value is true</p> 
     */
    @Builder.Default
    private Boolean isActive  = true;
}
