package lumi.insert.app.core.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.github.f4b6a3.uuid.UuidCreator;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated; 
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lumi.insert.app.core.entity.nondatabase.BaseAuditing;
import lumi.insert.app.core.entity.nondatabase.EmployeeRole;

/**
 * Representation class of database table {@code"employees"}. 
 * <p>Store Employee/User informations include credentials(hashed).<br>
 * Class can be implemented by{@code NoArgsConstructor, AllArgsConstructor and Builder}. </p>
 * 
 * @author KelvinKhodes
 * @since 1.0.0 
 */
@Entity(name = "employees")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
@Data 
@Audited
public class Employee extends BaseAuditing{
    
    /**
     * Token used to identify credentials and generate access token .
     ** <p>Generated by {@link UuidCreator#getTimeOrderedEpochFast()} .<br> Important: must not null and unique.</p> 
     */
    @Id 
    private UUID id;

    /**
     * Unique identifier for login. Max length 55 characters
     */
    @Column(unique = true, nullable = false, length = 55) 
    private String username;

    @Column(nullable = false)
    private String fullname;

    /**
     * Hashed authentication credential. 
     * Marked as {@code @NotAudited} to prevent plain-text or hash exposure in audit logs.
     */
    @Column(nullable = false)
    @NotAudited
    private String password;

    @Column(nullable = false)
    @NotAudited
    private LocalDateTime joinDate;

    /**
     * Metadata for security tracking. Stores the last known IP address 
     * during a successful login session.
     */
    @Column(nullable = true)
    private String lastIp;
    
    /**
     * Metadata for security tracking. Stores the last known Device 
     * during a successful login session.
     */
    @Column(nullable = true)
    private String lastDevice;

    @Builder.Default
    @Column(nullable = false)
    private boolean isActive = true;

    @Column(nullable = true)
    @NotAudited
    private String pictureUrl;

    @NotAudited 
    @OneToOne(mappedBy = "employee")
    private EmployeePicture employeePicture;

    /**
     * The default access level assigned to new employees.
     * Defaults to {@link EmployeeRole#CASHIER}.
     */
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private EmployeeRole role = EmployeeRole.CASHIER;

}
