package lumi.insert.app.core.entity;


import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
 
import org.hibernate.annotations.JdbcTypeCode; 
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.type.SqlTypes;
 
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lumi.insert.app.core.entity.nondatabase.BaseAuditing;

/**
 * Representation class of database table {@code"products"}. 
 * <p>Store product's detail informations.<br>
 * Class can be implemented by{@code NoArgsConstructor, AllArgsConstructor and Builder}. </p>
 * 
 * @author KelvinKhodes
 * @since 1.0.0 
 */
@Entity(name = "products")
@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Audited
public class Product extends BaseAuditing {
    
    /**
     * Unique identifier of entity .
     * <p>Auto generated by {@link  GeneratedValue} with {@link GenerationType#IDENTITY} strategy. Note: Assignment trigger after Entity saved</p>
     */ 
    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
    private Long id;

    /**
     * Product name. 
     ** <p>Important: must not null and unique.</p> 
     */
    @Column(unique = true, nullable = false)
    private String name;

    /**
     * Product base price based on average calculation. 
     ** <p>Important: must not null.</p> 
     */
    @Column(nullable = false)    
    private BigDecimal basePrice;

    @Column(nullable = false)
    private BigDecimal sellPrice;

    @Column(nullable = false)
    private BigDecimal stockQuantity;

    @Builder.Default
    private BigDecimal stockMinimum = BigDecimal.ZERO;
    
    /**
     * Relation to {@link Category} (categories).
     * <p>{@link ManyToOne} related, means one or more product can only related to one Category. </p>
     ** <p>Important: must not null.</p> 
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = true)
    @NotAudited
    private Category category;

    @Builder.Default
    private Boolean isActive = true;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @NotAudited 
    @Builder.Default
    private List<String> pictureUrl = new ArrayList<>();

    @OneToMany(mappedBy = "product")
    @Builder.Default
    @ToString.Exclude
    @NotAudited
    private List<ProductPicture> productPicture = new ArrayList<>();

    /**
     * Pre-query function used to normalize BigDecimal scale
     * <p>Rounding half up  and scaled by 4 for precise value</p>
     */
    @PrePersist
    @PreUpdate
    void normalizeDecimal(){
        this.basePrice = this.basePrice.setScale(4, RoundingMode.HALF_UP);
        this.sellPrice = this.sellPrice.setScale(4, RoundingMode.HALF_UP);
        this.stockMinimum = this.stockMinimum.setScale(4, RoundingMode.HALF_UP);
        this.stockQuantity = this.stockQuantity.setScale(4, RoundingMode.HALF_UP);
    }
}
