package lumi.insert.app.core.entity.nondatabase;

import lumi.insert.app.aspect.ActivityLogAspect;

/**
 * Enum for every request action that triggered by AOP {@link ActivityLogAspect}.  
 * 
 * @author KelvinKhodes
 * @since 1.0.0 
 */
public enum ActivityAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
 
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    STOCK_ADJUSTMENT, 
    
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,

    CUSTOMER_REGISTERED,
    CUSTOMER_UPDATED, 
    CUSTOMER_DELETED,

    SUPPLIER_REGISTERED,
    SUPPLIER_UPDATED, 
    SUPPLIER_DELETED,

    EMPLOYEE_REGISTERED,
    EMPLOYEE_UPDATED, 
    EMPLOYEE_DELETED,
 
    SUPPLY_ORDER_PLACED,   
    SUPPLY_ORDER_CANCELLED,
    SUPPLY_ORDER_UPDATED,
    SUPPLY_ITEM_REFUNDED,
    SUPPLY_PAYMENT_SETTLED, 
    SUPPLY_REFUND_RECEIVED, 
  
    TRANSACTION_CART_CREATED,
    TRANSACTION_ITEM_CARTED,  
    TRANSACTION_ITEM_DELETED, 
    TRANSACTION_ITEM_UPDATED,
    TRANSACTION_ORDER_PLACED,
    TRANSACTION_PAYMENT_RECEIVED, 
    TRANSACTION_ORDER_COMPLETED,
    TRANSACTION_ORDER_CANCELLED,
    TRANSACTION_REFUND_SETTLED,
 
    MEMO_CREATED, 
    MEMO_UPDATED,
    MEMO_DELETED,
    MEMO_READ,
     
    EXPORT_DATA
}
